name: Security Scan with Docker Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: |
        docker build -t myapp:latest .

  trivy-scan:
    name: Trivy scan on Docker Image
    runs-on: ubuntu-latest
    needs: build-image

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: docker build -t myapp:latest .

    - name: Scan image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: image
        image-ref: myapp:latest
        format: table
        output: trivy-image-report.txt
        severity: CRITICAL,HIGH

    - name: Upload Trivy scan result
      uses: actions/upload-artifact@v4
      with:
        name: trivy-image-report
        path: trivy-image-report.txt

  snyk-scan:
    name: Snyk scan on Docker Image
    runs-on: ubuntu-latest
    needs: build-image

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: docker build -t myapp:latest .

    - name: Install Snyk
      run: npm install -g snyk

    - name: Scan Docker image with Snyk
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: snyk container test myapp:latest --severity-threshold=high

  gitleaks-scan:
    name: Gitleaks scan for secrets
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Gitleaks
      run: |
        curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
        chmod +x gitleaks
        sudo mv gitleaks /usr/local/bin/gitleaks

    - name: Run Gitleaks
      run: |
        gitleaks detect --source . --report-format sarif --report-path gitleaks-report.sarif

    - name: Upload Gitleaks report
      uses: actions/upload-artifact@v4
      with:
        name: gitleaks-report
        path: gitleaks-report.sarif
