name: Security Scan with Docker Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  trivy-scan:
    name: Trivy scan on Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: docker build -t myapp:latest .

    - name: Scan image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: image
        image-ref: myapp:latest
        format: table
        output: trivy-image-report.txt
        severity: CRITICAL,HIGH

    - name: Upload Trivy scan result
      uses: actions/upload-artifact@v4
      with:
        name: trivy-image-report
        path: trivy-image-report.txt

  snyk-scan:
    name: Snyk scan on Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: docker build -t myapp:latest .

    - name: Install Snyk
      run: npm install -g snyk

    - name: Scan Docker image with Snyk
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: snyk container test myapp:latest --severity-threshold=high

  gitleaks-scan:
    name: Gitleaks scan for secrets
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Gitleaks
      uses: gitleaks/action-gitleaks@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Gitleaks report
      uses: actions/upload-artifact@v4
      with:
        name: gitleaks-report
        path: gitleaks-report.sarif
